##Flight Prediction EDA & Feature Engineering

In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [106]:
data_train = pd.read_excel('Data_Train.xlsx')
data_test = pd.read_excel('Test_set.xlsx')

In [107]:
final_df = pd.concat([data_train, data_test])
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [108]:
final_df["Date"] = pd.to_datetime(final_df["Date_of_Journey"]).dt.day
final_df["Month"] = pd.to_datetime(final_df["Date_of_Journey"]).dt.month
final_df["Year"] = pd.to_datetime(final_df["Date_of_Journey"]).dt.year

<ipython-input-108-0ba0990a3899>:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  final_df["Date"] = pd.to_datetime(final_df["Date_of_Journey"]).dt.day
<ipython-input-108-0ba0990a3899>:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  final_df["Month"] = pd.to_datetime(final_df["Date_of_Journey"]).dt.month
<ipython-input-108-0ba0990a3899>:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  final_df["Year"] = pd.to_datetime(final_df["Date_of_Journey"]).dt.year

In [109]:
final_df["Date"] = final_df["Date"].astype(int)
final_df["Month"] = final_df["Month"].astype(int)
final_df["Year"] = final_df["Year"].astype(int)

In [110]:
final_df.drop("Date_of_Journey", axis = 1, inplace = True)

In [111]:
final_df["Arrival_Time"] = final_df["Arrival_Time"].apply(lambda x: x.split(" ")[0])

In [112]:
final_df['Arrival_hour'] = final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_min'] = final_df['Arrival_Time'].str.split(':').str[1]
final_df["Arrival_hour"] = final_df["Arrival_hour"].astype(int)
final_df["Arrival_min"] = final_df["Arrival_min"].astype(int)
final_df.drop('Arrival_Time', axis = 1 , inplace = True)

In [113]:
final_df['Dept_hour'] = final_df['Dep_Time'].str.split(':').str[0]
final_df['Dept_min'] = final_df['Dep_Time'].str.split(':').str[1]
final_df["Dept_hour"] = final_df["Dept_hour"].astype(int)
final_df["Dept_min"] = final_df["Dept_min"].astype(int)
final_df.drop('Dep_Time', axis = 1 , inplace = True)

In [114]:
final_df['Total_Stops'] = final_df['Total_Stops'].map({'non-stop': 0, '1 stop': 1, '2 stop': 2, '3 stop': 3, '4 stop': 4}).fillna(1)

In [115]:
final_df.drop('Route', axis = 1, inplace = True)

In [116]:
final_df[final_df.Duration == "5m"]

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min
6474,Air India,Mumbai,Hyderabad,5m,1.0,No info,17327.0,6,3,2019,16,55,16,50
2660,Air India,Mumbai,Hyderabad,5m,1.0,No info,NaN,12,3,2019,16,55,16,50

In [117]:
final_df.drop(6474, axis = 0, inplace = True)
final_df.drop(2660, axis = 0, inplace = True)

In [118]:
final_df["Duration_hour"] = final_df['Duration'].str.split(" ").str[0].str.split('h').str[0]
final_df["Duration_hour"] = final_df["Duration_hour"].astype(int)
final_df.drop("Duration", axis = 1, inplace = True)

In [119]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [120]:
final_df["Airline"] = labelencoder.fit_transform(final_df["Airline"])
final_df["Source"] = labelencoder.fit_transform(final_df["Source"])
final_df["Destination"] = labelencoder.fit_transform(final_df["Destination"])
final_df["Additional_Info"] = labelencoder.fit_transform(final_df["Additional_Info"])